// automatically generated by xlsx-fbs, do not modify it. Modify xlsx-fbs/template/unity/*.cs instead.

using System.Collections.Generic;

namespace {{{ NAMESPACE }}}
{
       public class {{{ TABLE_CLASS }}}Table : TableLoaderBase<{{{ DATA_CLASS }}}>
    {
        protected override string AssetPath => "{{{ TABLE_NAME }}}";

        protected override void LoadData(TextAsset textAsset)
        {
            var root = {{{ TABLE_CLASS }}}.GetRootAs{{{ TABLE_CLASS }}}(_buffer);

            int length = root.{{{ DATA_CLASS }}}sLength;
            _dict = new Dictionary<uint, {{{ DATA_CLASS }}}>(length);
            _items = new {{{ DATA_CLASS }}}[length];

            for (int i = 0; i < length; i++)
            {
                var item = root.{{{ DATA_CLASS }}}s(i).Value; // Nullable
                _dict[item.Id] = item;
                _items[i] = item;
            }
        }
    }
}
