// <auto-generated>
//  automatically generated by xlsx-fbs, do not modify it. Modify xlsx-fbs/template/unity/*.cs instead.
// </auto-generated>

using Google.FlatBuffers;

namespace {{{ NAMESPACE }}}
{
    public class {{{ TABLE_LOADER_CLASS }}} : TableLoader<{{{ TABLE_CLASS }}}, {{{ DATA_CLASS }}}>
    {
        public static readonly {{{ TABLE_LOADER_CLASS }}} Instance = new();

        protected override string AssetPath => "{{{ TABLE_NAME }}}";
        protected override {{{ TABLE_CLASS }}} GetTableRoot(ByteBuffer buffer) => {{{ TABLE_CLASS }}}.GetRootAs{{{ TABLE_CLASS }}}(buffer);
        protected override int GetDataLength({{{ TABLE_CLASS }}} root) => root.{{{ DATA_CLASS_SNAKE_UPPER_CASE }}}sLength;
        protected override {{{ DATA_CLASS }}} GetData({{{ TABLE_CLASS }}} root, int index) => root.{{{ DATA_CLASS_SNAKE_UPPER_CASE }}}s(index).Value;
        protected override int GetDataId({{{ DATA_CLASS }}} data) => data.Id;
    }
}
