// automatically generated by xlsx-fbs, do not modify it

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export class {{{ CLASS_NAME }}}Const {
{{{ CONST_FIELD_LIST }}}
}