// automatically generated by xlsx-fbs, do not modify it

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';
{{{ IMPORT_CLASS_LIST }}}

const {{{ NAMESPACE }}} = {
{{{ CLASS_LIST }}}
};

// 挂到全局变量
if (typeof window !== 'undefined') {
  (window as any).flatbuffers = flatbuffers;
  (window as any).{{{ NAMESPACE }}} = {{{ NAMESPACE }}};
} else if (typeof global !== 'undefined') {
  (global as any).flatbuffers = flatbuffers;
  (global as any).{{{ NAMESPACE }}} = {{{ NAMESPACE }}};
}

// 可以导出给 Node 模块使用（CommonJS/ESM）
export { flatbuffers, {{{ NAMESPACE }}} };