// <auto-generated>
//  automatically generated by the xlsx-fbs, do not modify
// </auto-generated>

namespace {{{ NAMESPACE }}}
{
    public static class {{{ CLASS_NAME }}}Const
    {
{{{ CONST_FIELD_LIST }}}
    }
}
